### PR TITLE
Verify password

### PR DESCRIPTION
**Pull request by xBeastMode**

### CODE REVIEW

**Comment by applqpak** [comment]
@keithkfng

**Comment by keithkfng** [comment]
Yes, idiot. Why did you even think of leaving the org LOL

**Comment by xBeastMode** [comment]
Are you calling me an idiot?

**Comment by keithkfng** [comment]
No, not you. Do people understand English these days?

**Comment by xBeastMode** [comment]
Ok, I'm not a native English speak.

**Comment by keithkfng** [comment]
Ah I see

**Pull request merged**
