### PR TITLE
Create index.php

### PR DESCRIPTION
**Pull request by applqpak**

### CODE REVIEW

**Comment by keithkfng** [comment]
We actually need this on a web server, so it won't be inside the plugin...

**Comment by applqpak** [comment]
Ok.

**Comment by applqpak** [comment]
Where do I put it? imagicalmine.github.io?

**Comment by keithkfng** [comment]
If it's inside the plugin, the database credentials can be viewed in plain text by just extracting the plugin phar...

**Comment by keithkfng** [comment]
And just leave it inside a resources folder for now...

**Comment by applqpak** [comment]
I put it in imagicalmine.github.io

**Pull request closed without merging**
